#!/bin/sh /etc/rc.common

# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

#

START=75
SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
SERVICE_SIG_STOP="INT"

boot() {
	start
}

start() {
	cd /opt/alljoyn/gwagent
	service_start /usr/bin/alljoyn-gwagent --gwagent-policy-file=/etc/alljoyn/gwagent/gwagent.conf --apps-policy-dir=/etc/alljoyn/gwagent-apps
}

stop() {
	service_stop /usr/bin/alljoyn-gwagent
}